### ISSUE TITLE
Adding SVM written from scratch

### ISSUE THREAD

**Issue by imVivekGupta** [aribis369/ML-Starter-Pack#13]
Can I work on this?

**Comment by aribis369** [comment]
@imVivekGupta Yes you can definitely do it.

**Comment by Culeshovi** [comment]
@aribis369 I have implemented SVM from scratch. Please have look at my jupyter notebook.
https://github.com/Culeshovi/cs229/blob/master/SVM/SVMrbfkernel.ipynb
