### ISSUE TITLE
Adding k-means from scratch

### ISSUE THREAD

**Issue by sourojit** [aribis369/ML-Starter-Pack#18]
I will be working on k-means

**Comment by aribis369** [comment]
@sourojit KNN algo already implemented in the repo. You can create the jupyter notebook for it.

**Comment by sourojit** [comment]
@aribis369 I will be working on k-means algo and not KNN. I will also create the jupyter notebooks for KNN.

**Comment by aribis369** [comment]
@sourojit Oops! Sorry I think I named my program wrong. My program is the k-means( clustering algorithm ). Please change the name of the folder to k-means in place of knn. 
You can work on KNN if you are comfortable.
